### ISSUE TITLE
在离开container时，滚动条没有过渡

### ISSUE THREAD

**Issue by Cynic158** [linxx5599/scrollbar-vue2#2]
在鼠标移出scrollbar父元素container之后，组件没有消失过渡动画，组件有鼠标移入然后渐变显示的动画但是并没有鼠标移出的渐变消失动画，如果能加上就太好了

**Comment by Cynic158** [comment]
改了一下index.css的代码，应该是写错了，源代码：
```css
.scrollbar .scrollbar-fade-enter,
.scrollbar-fade-enter-leave-to {
  opacity: 0;
}

```
更正后的：
```css
.scrollbar .scrollbar-fade-enter,
.scrollbar-fade-leave-to {
  opacity: 0;
}

```
把-enter掐掉就行
